# This is a basic cloud build example. Replace REGION and PROJECT_ID
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/roimb-2025-appuser19/venusapp/venusapp:latest', '.' ]
images:
- 'us-central1-docker.pkg.dev/roimb-2025-appuser19/venusapp/venusapp:latest'

# 2. push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'us-central1-docker.pkg.dev/roimb-2025-appuser19/venusapp/venusapp:latest'
  ]
  
  # 3. deployed by Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 
    'deploy', 
    'venusapp-service',  # Cloud Run 服务名称
    '--image', 'us-central1-docker.pkg.dev/roimb-2025-appuser19/venusapp/venusapp:latest',
    '--region', 'us-central1',
    '--platform', 'managed', 
    '--allow-unauthenticated',  
    '--memory', '512Mi', 
    '--timeout', '300s'  
  ]
