# This is a basic cloud build example. Replace REGION and PROJECT_ID
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/roimb-2025-appuser19/venusapp/venusapp:latest', '.' ]
